---
title: "MATH3430-IMDb"
author: "MB"
date: "2025-11-19"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readxl)
library(dplyr)
library(ggplot2)
library(tidyr)
library(hexbin)
```

This is the code we used to load the oversized Excel files and clean the data that is used to create the graphs. NO ONE HAS TO RUN THIS PART OF THE CODE. JUST LOAD THE LIBRARIES AND THE READ_EXCEL.
```
raw_basics <- read_excel("title.basics.xlsx", na = '\\N')
raw_ratings <- read_excel("title.ratings.xlsx", na = '\\N')
```
```
movie_only_basics <- raw_basics %>% 
  filter(titleType == 'movie') %>% 
  select(-endYear, -titleType, -isAdult, -originalTitle) %>% 
  rename(releaseYear = startYear)

write_xlsx(movie_only_basics, path = "movie_only_basics.xlsx")
```
```
movie_and_rating_tidy <- inner_join(raw_ratings, movie_only_basics, by = "tconst")

write_xlsx(movie_and_rating_tidy, path = "movie_and_rating_tidy.xlsx")
```
```
movie_ratings <- movie_and_rating_tidy %>% 
  select(tconst:numVotes)

write_xlsx(movie_ratings, path = "movie_ratings.xlsx")
```
```{r}
movies <- read_excel("movie_only_basics.xlsx")
ratings <- read_excel("movie_ratings.xlsx")
movies_and_ratings <- read_excel("movie_and_rating_tidy.xlsx")
```

```{r}
movies <- movies %>%
  mutate(across(where(is.character),
                ~gsub("[^\x20-\x7E]", "", .x))) %>% 
  rename(title = primaryTitle)
```

```{r}
not_null_runtimes <- movies %>% 
  filter(!is.na(runtimeMinutes))

not_null_runtimes

not_null_genres <- movies %>%
  filter(!is.na(genres))

not_null_genres
```

```{r}
not_null_runtimes %>% 
  group_by(runtimeMinutes) %>% 
  summarize(n = n()) %>% 
  arrange(desc(n))
```

```{r}
movies_decade <- clean_movies %>% 
  mutate(decade = floor(releaseYear / 10) * 10) %>% 
  count(decade)

ggplot(movies_decade, aes(x = decade, y = n)) +
  geom_point() +
  geom_line(linewidth = 0.75, color = "blue") +
  labs(title = "Number of Movie Releases over Time",
       x = "Decade",
       y = "Number of Movie Releases") +
  theme(plot.title = element_text(hjust = 0.5))

#We have investigated this weird graph. The results we have came up with is that the data set is slightly out of date and as far as we know this graph accurately represents the d0.5 it has been given

```


```{r}
ggplot(not_null_runtimes, aes(x = runtimeMinutes)) +
  geom_histogram(bins = 30, na.rm = TRUE,  fill = "darkgreen", color = "lightgreen") +
  xlim(0, 250) +
  labs(title = "Distribution of Movie Runtimes",
       x = "Movie Runtime Minutes",
       y = "Count") +
  theme(plot.title = element_text(hjust = 0.5))
```

```{r}
#Expand Genres into multiple rows
movies_genre <- not_null_genres %>% 
  separate_rows(genres, sep = ",") %>% 
  mutate(genres = trimws(genres))

#Find top 10 genres overall
top_genres <- movies_genre %>% 
  count(genres, sort = TRUE) %>% 
  slice_head(n = 10) %>% 
  pull(genres)

#Calculate decade + filter for top genres
movies_genre_decade <- movies_genre %>% 
  filter(genres %in% top_genres) %>% 
  mutate(decade = floor(releaseYear / 10) * 10) %>%
  filter(!is.na(decade)) %>% 
  count(decade, genres) %>% 
  group_by(decade) %>% 
  mutate(prop = n / sum(n))

#Plot
ggplot(movies_genre_decade, aes(x = factor(decade), y = prop, fill = genres)) +
  geom_bar(stat = "identity", position = "fill", na.rm = T) +
  labs(
    title = "Genre Proportions by Decade",
    x = "Decade",
    y = "Proportion"
  )
```


```{r}
movies_and_ratings %>%
  mutate(runtime_cap = pmin(runtimeMinutes, 300)) %>% 
  ggplot(aes(x = releaseYear, 
             y = averageRating, 
             color = runtime_cap)) +
  geom_jitter(alpha = 0.15, size = 0.7, width = 0.3, height = 0.2) +
  scale_color_viridis_c(option = "plasma") +
  labs(
    title = "Rating vs Year Colored by Runtime (Capped at 300 Minutes)",
    x = "Year",
    y = "Rating",
    color = "Runtime (min)"
  )

```

Alternative to the above graph, using geom_hex to show the density a bit better to help witht the over plotting issue.
```{r}
movies_and_ratings %>%
  mutate(runtime_cap = pmin(runtimeMinutes, 300)) %>% 
  ggplot(aes(x = releaseYear, y = averageRating, z = runtime_cap)) +
  stat_summary_hex(fun = mean, bins = 30) +
  scale_fill_viridis_c(option = "plasma") +
  labs(
    title = "Rating vs Year — Hexbins Colored by Average Runtime",
    x = "Year",
    y = "Rating",
    fill = "Avg Runtime"
  )

```




